### ISSUE TITLE
plex.py not working

### ISSUE THREAD

**Issue by lukasf98** [ReenigneArcher/web2tv#12]
When I execute plex.py I get the following Error when calling the Website (I have an active Plex Pass):

https://epg.provider.plex.tv/grid?type=1%2C4&sort=beginsAt&endsAt%3E=1617451200&beginsAt%3C=1617537600&X-Plex-Token=_MY-TOKEN_&X-Plex-Language=en
```XML
<Error statusCode="403" error="Forbidden" message="'_MY_E-MAIL_' is NOT permitted to access restricted endpoint '/grid' on 'Plex Web/Chrome': Feature not permitted! Missing feature(s): cloud-livetv"/>
```

**Comment by ReenigneArcher** [comment]
I see you closed this. Do you mind commenting on how you resolved the issue?
