### ISSUE TITLE
Plutotv.py "encoding" error on m3u write attempt

### ISSUE THREAD

**Issue by kevtown** [ReenigneArcher/web2tv#13]
All requirements installed.

When attempting to write m3u file plutotv.py generates "encoding"  error.  However  --xml argument works fine.

$ python ./plutotv.py --m3u

hours: 10
offset: -0000
timezone: -0000
xmlFile: plutotv.xml
m3uFile: plutotv.m3u
prefix: 
startNumber: 1
keepNumber: False
streamlink: False
xml: False
m3u: True
Loading Grid for PlutoTV
url: https://service-channels.clusters.pluto.tv/v1/guide?start=2021-04-17T12:00:00-00:00&stop=2021-04-17T22:30:00-00:00
Channels Found: 301
m3u is ready to write
m3u is being created
Traceback (most recent call last):
  File "./plutotv.py", line 615, in <module>
    with open(m3u_destination, "w", encoding='utf-8') as f: #https://stackoverflow.com/a/42495690/11214013
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by ReenigneArcher** [comment]
Which version of python are you using?

**Comment by ReenigneArcher** [comment]
I am happy to re-open this if you are still having problems when using python 3+, but closing for now as you haven't responded.
