### ISSUE TITLE
error running plex.py

### ISSUE THREAD

**Issue by yarafie** [ReenigneArcher/web2tv#15]
getting an error running plex.py

run.log attached

[run.log](https://github.com/ReenigneArcher/web2tv/files/7615740/run.log)

**Comment by ReenigneArcher** [comment]
Please paste your log inside a comment here. https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

Alternatively use github [gists](https://gist.github.com/) or pastebin and send me the link.

**Comment by yarafie** [comment]
Parts of log pasted below couldn't figure out how to use the above gists wouldn't let me attach file. I removed the token and replaced it with <My Token> for the purpose of the log below. Please not I was able to create only the m3u its epg generation that is having problem

**Comment by yarafie** [comment]
token: <My Token>
language: en
days: 1
pastdays: 0
xmlFile: plex2.xml
m3uFile: plex2.m3u
startNumber: 1
keepNumber: False
streamlink: False
xml: True
m3u: True
Loading Grid for PlexTV, day: 1/1
url[1]: https://epg.provider.plex.tv/grid?type=1%2C4&sort=beginsAt&endsAt%3E=1638162000&beginsAt%3C=1638248400&X-Plex-Token=<My Token>&X-Plex-Language=en
Channels Found: 206
Programs Found: 6904
Streams Found: 206
Are We There Yet? will be added to the xml.1/205
undefined will be added to the xml.2/205
undefined will be added to the xml.3/205
Crackle will be added to the xml.4/205
MOVIESPHERE will be added to the xml.5/205
Popcornflix will be added to the xml.6/205
.
.
.
undefined will be added to the xml.198/205
YG TV will be added to the xml.199/205
Loop Music Videos will be added to the xml.200/205
Party Tyme Karaoke will be added to the xml.201/205
Party Tyme Karaoke will be added to the xml.202/205
Flash will be added to the xml.203/205
Latido Music will be added to the xml.204/205
undefined will be added to the xml.205/205
Are We There Yet?,ratingKey: 6198b0f1129d7782c983190f will be added to the xml.1/6903
Are We There Yet?,ratingKey: 6198b0f1129d7782c9831910 will be added to the xml.2/6903
Are We There Yet?,ratingKey: 6198b0f1129d7782c9831911 will be added to the xml.3/6903
Are We There Yet?,ratingKey: 6198b0f2129d7782c9831912 will be added to the xml.4/6903
Are We There Yet?,ratingKey: 6198b0f2129d7782c9831913 will be added to the xml.5/6903
Are We There Yet?,ratingKey: 6198b0f2129d7782c9831914 will be added to the xml.6/6903
Are We There Yet?,ratingKey: 6198b0f2129d7782c9831915 will be added to the xml.7/6903
.
.
.
.
Kids Pang TV,ratingKey: 60d52290066687002d80885a will be added to the xml.4759/6903
The Law of Moises,ratingKey: 614b9175487bcfcaee82c394 will be added to the xml.4760/6903
The Adventures of Ozzie and Harriet,ratingKey: 619ed83fb252eccc5aef8e68 will be added to the xml.4761/6903
The Adventures of Ozzie and Harriet,ratingKey: 619ed83fb252eccc5aef8e69 will be added to the xml.4762/6903
The Adventures of Ozzie and Harriet,ratingKey: 619ed83fb252eccc5aef8e6a will be added to the xml.4763/6903
The Adventures of Swiss Family Robinson,ratingKey: 619ed83fb252eccc5aef8e6b will be added to the xml.4764/6903
The Adventures of Swiss Family Robinson,ratingKey: 619ed83fb252eccc5aef8e6b will be added to the xml.4765/6903
The Dick Van Dyke Show,ratingKey: 619ed840b252eccc5aef8e6d will be added to the xml.4766/6903
My Classic Car,ratingKey: 619ed849b252eccc5aef8e72 will be added to the xml.4767/6903
My Classic Car,ratingKey: 619ed849b252eccc5aef8e72 will be added to the xml.4768/6903
It's a Miracle,ratingKey: 619ed840b252eccc5aef8e6f will be added to the xml.4769/6903
It's a Miracle,ratingKey: 619ed840b252eccc5aef8e70 will be added to the xml.4770/6903
Young Charlie Chaplin,ratingKey: 619ed840b252eccc5aef8e71 will be added to the xml.4771/6903
My Classic Car,ratingKey: 6170b3b379cb80665079de23 will be added to the xml.4772/6903
My Classic Car,ratingKey: 6170b3b379cb80665079de23 will be added to the xml.4773/6903
The Enid Blyton Adventure Series,ratingKey: 619ed839b252eccc5aef8e61 will be added to the xml.4774/6903
The Enid Blyton Adventure Series,ratingKey: 619ed839b252eccc5aef8e61 will be added to the xml.4775/6903
The Enid Blyton Adventure Series,ratingKey: 619ed839b252eccc5aef8e62 will be added to the xml.4776/6903
The Legend of William Tell,ratingKey: 619ed83db252eccc5aef8e66 will be added to the xml.4777/6903
The Legend of William Tell,ratingKey: 619ed83db252eccc5aef8e66 will be added to the xml.4778/6903
Inventions that Shook the World,ratingKey: 61836103b49a9930f916f87b will be added to the xml.4779/6903
Inventions that Shook the World,ratingKey: 61836103b49a9930f916f87b will be added to the xml.4780/6903
My Classic Car,ratingKey: 61960e43bb0a3bb1de206fcb will be added to the xml.4781/6903
The Legend of William Tell,ratingKey: 61960e22bb0a3bb1de206fb8 will be added to the xml.4782/6903
The Legend of William Tell,ratingKey: 619ed83db252eccc5aef8e67 will be added to the xml.4783/6903
Made for Each Other,ratingKey: 61960e42bb0a3bb1de206fc9 will be added to the xml.4784/6903
My Classic Car,ratingKey: 619d869264db0ebdb18bb384 will be added to the xml.4785/6903
My Classic Car,ratingKey: 619ae3a69bb419970842b2d3 will be added to the xml.4786/6903
William Shatner's A Twist in the Tale,ratingKey: 619ed838b252eccc5aef8e56 will be added to the xml.4787/6903
William Shatner's A Twist in the Tale,ratingKey: 619ed838b252eccc5aef8e57 will be added to the xml.4788/6903
Maricela,ratingKey: 61960e43bb0a3bb1de206fcc will be added to the xml.4789/6903
The Legend of William Tell,ratingKey: 614b9161487bcfcaee82c31f will be added to the xml.4790/6903
400 Thunder Drag Racing Series,ratingKey: 6156c9c55b95569c5c70a5ef will be added to the xml.4791/6903
Traceback (most recent call last):
  File "/storage/emulated/0/IPTV/web2tv/plex.py", line 554, in <module>
    xml += '\n\t\t<rating system="' + rating_system[program_list[x]['contentRating'].lower()] + '">' #rating system
KeyError: 'tvpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/IPTV/web2tv/plex.py", line 560, in <module>
    errorDetails_contentRating.append('Title: ' + program_list[x]['title'] + ', GrandparentTitle: ' + program_list[x]['grandparentTitle'])
KeyError: 'grandparentTitle'

**Comment by ReenigneArcher** [comment]
Can you try the version from this branch? https://github.com/ReenigneArcher/web2tv/tree/20210822

Also, which version of python are you using?

**Comment by yarafie** [comment]
Python 3.10.0 under Termux 

will give the suggested branch a try and will let you know

**Comment by yarafie** [comment]
Well downloaded the suggested branch and after jumping through a few hoops to get the python requirements installed, managed to run both pluto.py and plex.py. Both ran at least without errors generating both m3u and xml.

However something is a little off so I started digging into the generated files and the python code.

Just started wading through it but first thing I noticed is in the generated pluto.m3u was only showing 1 channel when I loaded it into some IPTV players.

Looking into the m3u file itself and the py code for pluto.py I think you missed adding  \n at the end of the text on line 419 which was then not having the next channel start on a new line. That fixed it I am now getting 351 channels appearing. The xml loaded fine in the players I'm using so also seems to be fine on the surface.

Plex though the xml seems odd and did not  seem to show up in any of the players I'm using although lists of channels appear but no epg. didn't have the time to dig into further yet.

**Comment by yarafie** [comment]
Oh noticed that you added ustvgo.py but since I'm running in termux on my android phone couldn't test it since I think it needs geckodrive which I don't think there is a version for android. I might try it later with an anlinux Ubuntu on android in termux later.

**Comment by yarafie** [comment]
For the Plex epg I haven't had time to look into it but you can compare your output to the below epg which when I added it to my iptv player it showed up for your m3u

https://i.mjh.nz/Plex/all.xml.gz

**Comment by ReenigneArcher** [comment]
Good catch on the new line issue here: https://github.com/ReenigneArcher/web2tv/blob/514948213c96123ab6a6be52e4387f90a44b0b1a/plutotv.py#L419 ... I've updated this already. I personally use the streamlink argument as the other players I've tried cannot handle pluto once it hits a commercial break.

Not sure about all the requirements and how they would run on Android to be honest.

If you'd like me to review your outputs you're going to have to put it into a gist. You just copy and paste the text to the gist. Then click create secret gist and send me the link. You can delete it after I review if you like.

Also, this is one of my earliest experiences with python so definitely a lot that could be improved I'm sure.

**Comment by yarafie** [comment]
Hi. 
Just to confirm  both plex and pluto m3u get generated and work fine.
The epg guides also get generated for both plex and Pluto but I think the plex epg is not being created correctly.

Let me explain by taking an example  from the generated plex2.xml file. I will attach it below and explain now

If you look at the example below you first have the block that defines the channel (There should only be one of these per channel) then you will find multiple program blocks.
What links the channel block with the program blocks is 

<channel id="Are We There Yet?">  in the channel block
and 
<programme 
start="20211202110230 +0000" stop="20211202112638 +0000" channel="1">

as you can see above channel="1" in program block does not match <channel id="Are We There Yet?"
so in an iptv player they won't be linked and won't show up

[plex2.txt](https://github.com/ReenigneArcher/web2tv/files/7653276/plex2.txt)

**Comment by yarafie** [comment]
-----------------------------------
Sample from plex2.xml
-----------------------------------
<channel id="Are We There Yet?">
		<display-name>Are We There Yet?</display-name>
		<display-name>Are We There Yet?</display-name> <display-name>5e20b730f2f8d5003d739db7-612919784f53e1002c9aa219</display-name>
		<icon src="https://provider-static.plex.tv/epg/images/ott_channels/logos/AreWeThereYet_logo_dark.png" />
	</channel>

<programme 
start="20211202110230 +0000" stop="20211202112638 +0000" channel="1">
		<title lang="en">Are We There Yet?</title>
		<desc lang="en">Nick tries to become a more effective parent, so he pushes Kevin and Lindsey to become better people.</desc>
		<length units="seconds">1448</length>
		<date>20121002</date>
		<sub-title lang="en">The Tiger Dad Episode</sub-title>
		<icon src=
		"https://provider-static.plex.tv/epg/images/thumbnails/AreWeThereYet_Channel_artwork_vertical.jpg" />
		<episode-num system="onscreen">S03E12</episode-num>
		<episode-num system="common">S03E12</episode-num>
		<episode-num system="xmltv_ns">2.11.</episode-num>
		<episode-num system="plex">61975f6f8770ad9125f9f54e</episode-num>
		<rating system="n/a">
			<value>NR</value>
			<icon src=
			"https://loyoladigitaladvertising.files.wordpress.com/2014/02/nr-logo.png" />
		</rating>
		<previously-shown start="20121002 +0000" />
		<video>
			<present>yes</present>
			<aspect>16:9</aspect>
			<quality>HDTV</quality>
		</video>
</programme>

**Comment by yarafie** [comment]
> -----------------------------------
Sample from plex2.xml
-----------------------------------
<channel id="Are We There Yet?">
		<display-name>Are We There Yet?</display-name>
		<display-name>Are We There Yet?</display-name> <display-name>5e20b730f2f8d5003d739db7-612919784f53e1002c9aa219</display-name>
		<icon src="https://provider-static.plex.tv/epg/images/ott_channels/logos/AreWeThereYet_logo_dark.png" />
	</channel>

<programme 
start="20211202110230 +0000" stop="20211202112638 +0000" channel="1">
		<title lang="en">Are We There Yet?</title>
		<desc lang="en">Nick tries to become a more effective parent, so he pushes Kevin and Lindsey to become better people.</desc>
		<length units="seconds">1448</length>
		<date>20121002</date>
		<sub-title lang="en">The Tiger Dad Episode</sub-title>
		<icon src=
		"https://provider-static.plex.tv/epg/images/thumbnails/AreWeThereYet_Channel_artwork_vertical.jpg" />
		<episode-num system="onscreen">S03E12</episode-num>
		<episode-num system="common">S03E12</episode-num>
		<episode-num system="xmltv_ns">2.11.</episode-num>
		<episode-num system="plex">61975f6f8770ad9125f9f54e</episode-num>
		<rating system="n/a">
			<value>NR</value>
			<icon src=
			"https://loyoladigitaladvertising.files.wordpress.com/2014/02/nr-logo.png" />
		</rating>
		<previously-shown start="20121002 +0000" />
		<video>
			<present>yes</present>
			<aspect>16:9</aspect>
			<quality>HDTV</quality>
		</video>
</programme>

**Comment by ReenigneArcher** [comment]
There can be multiple channel display names according to the standard. The program is supposed to link by channel id. In my case the id is the channel number.

```xml
	<channel id="3002">
		<display-name>PLEX.TV.Are We There Yet?</display-name>
		<display-name>Are We There Yet?</display-name>
		<display-name>5e20b730f2f8d5003d739db7-612919784f53e1002c9aa219</display-name>
		<icon src="https://provider-static.plex.tv/epg/images/ott_channels/logos/AreWeThereYet_logo_dark.png" />
	</channel>
	<programme start="20211203135726 +0000" stop="20211203142334 +0000" channel="3002">
		<title lang="en">Are We There Yet?</title>
		<desc lang="en">Nick helps a coworker by ghostwriting love letters for a woman on a dating website who turns out to be Gigi.</desc>
		<length units="seconds">1568</length>
		<date>20121112</date>
		<sub-title lang="en">The Cyrano Episode</sub-title>
		<icon src="https://provider-static.plex.tv/epg/images/thumbnails/AreWeThereYet_Channel_artwork_vertical.jpg" />
		<episode-num system="onscreen">S03E38</episode-num>
		<episode-num system="common">S03E38</episode-num>
		<episode-num system="xmltv_ns">2.37.</episode-num>
		<episode-num system="plex">6198b0f1129d7782c983190e</episode-num>
		<rating system="n/a">
			<value>NR</value>
			<icon src="https://loyoladigitaladvertising.files.wordpress.com/2014/02/nr-logo.png" />
		</rating>
		<category lang="en">Comedy</category>
		<previously-shown start="20121112 +0000" />
		<video>
			<present>yes</present>
			<aspect>16:9</aspect>
			<quality>HDTV</quality>
		</video>
	</programme>
```

Display names are used by the software for channel mapping. There doesn't seem to be any standard for how they do this, or at least the two different players I've used are completely different in this manner.

Can you send the arguments you passed to the script? I don't need the token of course. Seems to be a difference in output between mine and yours.

**Comment by ReenigneArcher** [comment]
I just pushed an update. I believe it will fix your issue. Please test and let me know.

**Comment by yarafie** [comment]
> I just pushed an update. I believe it will fix your issue. Please test and let me know.

Just tested it. Works thanks. 

I'm also just learning python and all this IPTV stuff. 

Interested in what you mentioned using streamlink can you point me in the right direction?

**Comment by ReenigneArcher** [comment]
Cool, glad it's fixed. Feel free to review the scripts and make improvements. PRs are always welcome.

I'll probably push this branch into main before long.

[Streamlink](https://streamlink.github.io/)

I feed my streams into Xteve. Xteve is an HDHR emulator that acts as a proxy for m3u streams and other HDHR devices... For plutotv, I use Streamlink as the buffer which outputs the video stream to stdout. I think this will help if you want to use xteve also. https://github.com/streamlink/streamlink/discussions/3430
