### ISSUE TITLE
getting error running plex.py when creating xml

### ISSUE THREAD

**Issue by yarafie** [ReenigneArcher/web2tv#17]
getting error running plex.py when creating xml (using branch not main)

creating m3u is fine

below is top and bottom of run upto error received I XXXX my token

$  python3 plex.py -t=XXXXXXXXXXXXXXXXXX -d=1 -x="plex2us.xml" --xml 

Loading Grid for PlexTV, day: 1/1
url[1]: https://epg.provider.plex.tv/grid?type=1%2C4&sort=beginsAt&endsAt%3E=1640962800&beginsAt%3C=1641049200&X-Plex-Token=XXXXXXXXXXXX&X-Plex-Language=en
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Unknown Title
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
Journy's Bourdain All Day
..
..
Best TV Ever ID
Return of the Androids
Lure of Light
Freezing Torture
The Destroying Ray
Traceback (most recent call last):
  File "/storage/emulated/0/IPTV/web2tv-20210822/plex.py", line 543, in <module>
    main()
  File "/storage/emulated/0/IPTV/web2tv-20210822/plex.py", line 438, in main
    xmltv_ns = f'{xmltv_ns}.{int(program[number]) -1}.'
ValueError: invalid literal for int() with base 10: '0-1'

**Comment by ReenigneArcher** [comment]
I was able to replicate the issue and fixed in the 202110822 branch.

**Comment by yarafie** [comment]
You are the man.  Tested it and works great now

**Comment by ReenigneArcher** [comment]
> You are the man. Tested it and works great now

FYI, I've merged everything into the main branch now. Thanks!
