### ISSUE TITLE
invalid syntax with path

### ISSUE THREAD

**Issue by merrychrishna** [ReenigneArcher/web2tv#20]
### Describe the Bug

invalid syntax in path

### Code Snippets

```python
>>> m3u_modder.py -i C:\cygwin64\home\user\PlutoIPTV\playlist.m3u8 -o C:\cygwin64\home\user\xteve2\PlutoXteveStreamlink.m3u
  File "<stdin>", line 1
    m3u_modder.py -i C:\cygwin64\home\user\PlutoIPTV\playlist.m3u8 -o C:\cygwin64\home\user\xteve2\PlutoXteveStreamlink.m3u
                     ^
SyntaxError: invalid syntax
```

### Operating System and Version

windows 10

### Python Version

Python 3.7.9

**Comment by ReenigneArcher** [comment]
You need to prefix python scripts with your python binary. What that is depends on how you've installed python, but most likely `python` will work.

```batch
python m3u_modder.py <args>
```

**Comment by merrychrishna** [comment]
i solved it by exiting python and typing the command
