### ISSUE TITLE
http-user-agent=xteve could not be found.

### ISSUE THREAD

**Issue by merrychrishna** [ReenigneArcher/web2tv#21]
### Describe the Bug

when i run the mod m3u in xteve through emby, xteve shows this error and will not start the stream

### Code Snippets

```python
VLC log:                error: The specified stream(s) ':http-user-agent=xteve' could not be found.
```

### Operating System and Version

windows 10

### Python Version

Python 3.7.9

**Comment by ReenigneArcher** [comment]
You are using the script wrong. Basically all this script does is prepend the stream urls with the protocol required for streamlink.

For example, `hls://` could be prepended. See here: https://streamlink.github.io/cli.html#supported-streaming-protocols

The script does nothing more than that as far as other streamlink arguments.

**Comment by merrychrishna** [comment]
i had the same error with your plutotv.py script. the fix was to remove the word xteve from the useragent field in xteve
