### ISSUE TITLE
pluto tv 80s rewind channel freezing

### ISSUE THREAD

**Issue by merrychrishna** [ReenigneArcher/web2tv#28]
### Describe the Bug

only the pluto tv 80s Rewind channel is freezing for me every time it goes to commercial. this is the reason i switched from the old pluto tv script to use your pluto tv script to be used with xteve and streamlink.
 would you happen to know what i can try? the other channels make it through the commercials fine though.

### Expected Behavior

the 80s channel should transition through the commercial and then continue playing the show

### Additional Context

it seems to happen exactly before a commercial starts, is when it freezes forever. i never make it to the pluto tv screen saver commercial. but the channel plays fine up until the commercial.

also if i stop the channel and start it again, the channel plays fine up until the commercial again, then freezes again.

### Operating System and Version

windows 10,  regual android 9

### Python Version

Python 3.7.9

**Comment by ReenigneArcher** [comment]
Try asking in Streamlink. This project does nothing except create an m3u playlist.

**Comment by merrychrishna** [comment]
oh ok

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/182273378-c70fb734-a893-4a49-ae9d-1ea6a5e5dfad.png)
this what someone said at streamlink discusssion but i dont know where to find segment names

**Comment by ReenigneArcher** [comment]
@merrychrishna the pluto tv plugin for streamlink should already handle this... but again, that is not part of this repo, so not sure how else to help you.

**Comment by merrychrishna** [comment]
@ReenigneArcher i have new info for you. when i run this command in windows cmd prompt
 ###streamlink -l debug "https://pluto.tv/live-tv/80s-rewind" best###
the channel is recognized by the new built in pluto tv plugin that is built into streamlink 4.2.0-2 and plays fine straight through all ads or commercial breaks which is the expected behaviour. so that tells me theres no problem with streamlink.

i dont want to insult you by saying the problem is your script but can you please looks at your script for the 80s rewind US channel to see if anything is different with that part of your code comapred to the 70s and 90s channel? because the 70s and 90s channels dont have that problem with the freezing when it goes to commercial or ad breaks.

to give you more info. here is the command i run to create the m3u and epg with your pluto.py
###python C:\cygwin64\home\user\xteve2\web2tv-main\plutotv.py -e 12 -x C:\cygwin64\home\user\xteve2\streamlinkPlutoEpg.xml --xml -m C:\cygwin64\home\user\xteve2\streamlinkPlutoM3U.m3u --m3u --streamlink###

and if you want to try to test it in xteve like what im doing, here are the streamlink settings you need to put in xteve:

PLAYLIST
playlist tuners = 1

SETTINGS
number of tuners = 10
EPG source = XEPG

Schedule for updating (Playlist, XMLTV, Backup): = 0600,1100,1600,2100,0200
Stream Buffer:= ffmpeg or VLC                                                          <--MINE IS SET TO FFMPEG
Buffer Size: = 1mb
Timeout for new client connections: = 500
User Agent: = (blank)                                                                    <--THIS IS IMPORTANT OR THE STREAM WONT START
FFmpeg Binary Path: = C:\Program Files\Streamlink\bin\streamlink.exe
FFmpeg Options: = --stdout --loglevel info [URL] --default-stream best
VLC / CVLC Binary Path: = C:\Program Files\Streamlink\bin\streamlink.exe
VLC / CVLC Options: = --stdout --loglevel info [URL] --default-stream best

**Comment by ReenigneArcher** [comment]
Share your m3u

**Comment by merrychrishna** [comment]
[streamlinkPlutoM3U.zip](https://github.com/ReenigneArcher/web2tv/files/9244998/streamlinkPlutoM3U.zip)

**Comment by ReenigneArcher** [comment]
There are no per channel code differences. Every channel is processed the exact same way.

**Comment by merrychrishna** [comment]
ok. so theres probably a problem with emby then because thats all thats left to test. i just dont know what to look for.

**Comment by merrychrishna** [comment]
or maybe its a problem with xteve showing this error
2022/08/02 15:33:42 [xTeVe] [ERROR] remove C:\cygwin64\tmp\xteve\2022-08-FYRA-7OOS04\MFYC9U6Z1W7ZFXY0J855\b079e5a90efa83a7cec545401701c944\\652.ts: The process cannot access the file because it is being used by another process. (Temporary buffer files could not be deleted) - EC: 4005

but i cant find any resolution to that error for xteve

**Comment by merrychrishna** [comment]
nevermind, i found the problem. the problem is the new update for the emby for android tv app. emby has 2 apps. one is called emby for android tv, the other one is just called emby for android. i tried emby for android and theres no problem with the 80s rewind channel commercials. but emby for android has a slower ui and the live tv guide seems unfinished. so i will open a thread on the emby forum to see if they will fix emby for android tv.

**Comment by ReenigneArcher** [comment]
This is the url my script generates for this channel. `https://pluto.tv/live-tv/80s-rewind` same one you used to test in streamlink directly. Your xteve settings might be causing the issue. Too much or too little buffer. I'm not very familiar with emby, but I know with Plex it expects live tv to be `ts`. My scripts do not re-encode anything so if it's not in ts it will give problems (at least in Plex).

**Comment by merrychrishna** [comment]
ok ill try adjusting the xteve buffer before i report to emby devs. thanks
