### ISSUE TITLE
Add zap2it

### ISSUE THREAD

**Issue by ReenigneArcher** [ReenigneArcher/web2tv#9]
Example url: https://tvlistings.zap2it.com/api/grid?lineupId=USA-DITV-DEFAULT&timespan=6&headendId=DITV&country=USA&timezone=&device=-&postalCode=28278&isOverride=true&time=1609171200&pref=16%2C256&userId=-&aid=gapzap&languagecode=en

This could be of use... https://github.com/edit4ever/script.module.zap2epg

Also this: https://web.archive.org/web/20200426004001/http://zap2xml.awardspace.info/

**Comment by Protektor-Desura** [comment]
You can find a python version of the Zap2It script here:
https://github.com/daniel-widrick/zap2it-GuideScraping
